<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Statecharts"
    nsURI="http://statechart" nsPrefix="Statecharts">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textboxes" upperBound="-1"
        eType="#//TextArea" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
        eType="#//SuperState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//State">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="ellipse"/>
      <details key="color" value="0,0,0"/>
      <details key="label.placement" value="outer"/>
      <details key="border.color" value="0,0,0"/>
      <details key="size" value="1,1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State">
    <eAnnotations source="gmf.node">
      <details key="label" value=" name "/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="ellipse"/>
      <details key="color" value="255,255,255"/>
      <details key="label.placement" value="outer"/>
      <details key="border.color" value="0,0,0"/>
      <details key="size" value="1,1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalState" eSuperTypes="#//State">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rounded"/>
      <details key="color" value="230,230,250"/>
      <details key="border.color" value="0,0,0"/>
      <details key="size" value="1,1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Action" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="gmf.label">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperState" eSuperTypes="#//State">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="color" value="255,240,245"/>
      <details key="border.color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="border.color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedstates" upperBound="-1"
        eType="#//State" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eAnnotations source="gmf.link">
      <details key="label" value="name"/>
      <details key="source" value="source"/>
      <details key="target" value="destination"/>
      <details key="target.decoration" value="arrow"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextArea">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="label.placement" value="internal"/>
      <details key="color" value="245,245,245"/>
      <details key="border.color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="include" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="gmf.label">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="gmf.label">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="gmf.label">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
