../config/Os_application_dependent_code.c: ../config/Os_application_dependent_code.c.sh $(subst ../config/Os_application_dependent_code.c,,$(wildcard ../*.c ../*/*.c ../*/*/*.c))
	../config/Os_application_dependent_code.c.sh

$(OBJS): ../config/Os_application_dependent_code.c

# \s\+ would be the right seperator, but Linux wants '\+' and Windows wants '+'
FEATURES_MD5 = $(shell md5sum ../config/Os_cfg_features.h | sed -ne 's/^\([0-9a-fA-F]\+\)\s*.*$$/\1/p')

ifeq ($(FEATURES_MD5),)
  $(error couldn't determine MD5 of Os_cfg_features.h)
else
  $(shell echo FEATURES_MD5: $(FEATURES_MD5) >&2)
endif

all: libcaRtos-$(FEATURES_MD5).a

libcaRtos-$(FEATURES_MD5).a: libXMegaOS.a
	cp $< $@
