# add the caRtos library
MD5_CMD = $(shell which md5sum || which md5)
FEATURES_MD5 = $(shell if which md5sum &>/dev/null; then md5sum ../config/Os_cfg_features.h | sed -ne 's/^\([0-9a-fA-F]\+\)\s\+.*$$/\1/p' ; else md5 -q ../config/Os_cfg_features.h ; fi)
LIBS += -lcaRtos-$(FEATURES_MD5)

# make sure that Os_cfg_application.c is compiled and linked to the application
ifeq ($(findstring Os_cfg_application.o,$(OBJS)),)
	OBJS += Os_cfg_application.o
endif
