/*
 * Os_application_dependent_code.c
 *
 * generated by script
 */
 
// This file contains code that should be part of the OS, but depends on the
// application configuration (e.g. count of TCBs). It must be compiled for
// each application.

// This file is generated by the shell script Os_application_dependent_code.c.sh
// DO NOT MODIFY IT !!!

// You can mark application specific code like this:


// will be compiled in Os_application_dependent_code.c:
#ifdef APPLICATION_DEPENDENT_CODE
// your includes (including the directory name!)
// your code
#endif	// end of APPLICATION_DEPENDENT_CODE


#include "config/Os_cfg_application.h"



// from file os/drivers/USART.c:

#include "IPC/queue.h"

#ifndef USART_TRANSMIT_QUEUE_LENGTH
#	warning USART_TRANSMIT_QUEUE_LENGTH not set, using default value of 10
#	define USART_TRANSMIT_QUEUE_LENGTH 10
#endif

// reserve waiting places for "writers" for all
// tasks except the USART transmitter
QUEUE(usart,USART_TRANSMIT_QUEUE_LENGTH,1,OS_NUMBER_OF_TCBS_DEFINE-1);


// from file os/drivers/Timer.c:


#include "config/Os_config.h"
#include "drivers/Timer.h"

// Initializes Timer1 with a prescaling and a compare match value
void TimerInit(void)
{
	OCR1A = OS_TIMER_COMPARE_VALUE;
	TCNT1 = 0;
	TCCR1A = 0;
	TCCR1B = (1 << WGM12) //CTC
	       | OS_TIMER_PRESCALE;
	TIMSK1 = (1 << OCIE1A); // Enable Output Compare Interrupt Match for Timer1/ChannelA.
	
	//TCC0.CTRLA = OS_TIMER_PRESCALE;							// Prescale (user setting)
	//TCC0.CTRLB = TC0_CCAEN_bm;								// Compare or Capture enable for counter A
	//TCC0.INTCTRLB = TC0_CCAINTLVL0_bm | TC0_CCAINTLVL1_bm;	// High priority
	//TCC0.PER = OS_TIMER_COMPARE_VALUE;							// Compare value (user setting)
	//PMIC.CTRL |= (1<<PIN0)|(1<<PIN1)|(1<<PIN2);
}



// from file os/config/Os_application_dependent_code.c:

// your includes (including the directory name!)
// your code
