/*
 * Os_application_dependent_code.c
 *
 * generated by script
 */

// This file contains code that should be part of the OS, but depends on the
// application configuration (e.g. count of TCBs). It must be compiled for
// each application.

// This file is generated by the shell script Os_application_dependent_code.c.sh
// DO NOT MODIFY IT !!!

// You can mark application specific code like this:


// will be compiled in Os_application_dependent_code.c:
#ifdef APPLICATION_DEPENDENT_CODE
// your includes (including the directory name!)
// your code
#endif	// end of APPLICATION_DEPENDENT_CODE


#include "config/Os_cfg_application.h"



// from file os/drivers/USART.c:

#include "IPC/queue.h"

#ifndef USART_TRANSMIT_QUEUE_LENGTH
#	warning USART_TRANSMIT_QUEUE_LENGTH not set, using default value of 10
#	define USART_TRANSMIT_QUEUE_LENGTH 10
#endif

// reserve waiting places for "writers" for all
// tasks except the USART transmitter
QUEUE(usart,USART_TRANSMIT_QUEUE_LENGTH,1,OS_NUMBER_OF_TCBS_DEFINE-1);


// from file os/config/Os_application_dependent_code.c:

// your includes (including the directory name!)
// your code
