#include<avr/wdt.h>

int main() {
	HIGH(FIRST_GEAR);
	HIGH(SECOND_GEAR);
	HIGH(THIRD_GEAR);
	HIGH(FOURTH_GEAR);

	OUTPUT(FIRST_GEAR);
	OUTPUT(SECOND_GEAR);
	OUTPUT(THIRD_GEAR);
	OUTPUT(FOURTH_GEAR);
}
